import { v } from "convex/values";
import { internal } from "../_generated/api";
import type { Doc, Id } from "../_generated/dataModel";
import { action, internalAction, internalQuery, mutation, query, type QueryCtx } from "../_generated/server";
import { jobSummaries, predictMinutesLeft, stageStats } from "../generation/core/stats";
import { runAiTry, runCodeStage } from "../generation/jobs";
import { checkOutput, getStage, stages } from "../generation/stages";
import { workflow } from "../generation/workflow";
import { isDevUser, requireDevUser } from "../lib/auth";

// Dev-only generation tester. Every public function here checks the DEV_TOOL_USER_IDS allowlist.

const difficulty = v.union(v.literal("easy"), v.literal("normal"), v.literal("hard"));

/** Tells the page whether the current user may use the tester (and their id, to add to the allowlist). */
export const access = query({
  args: {},
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) return { signedIn: false, allowed: false, userId: null };
    return { signedIn: true, allowed: isDevUser(identity.subject), userId: identity.subject };
  },
});

export const listStages = query({
  args: {},
  handler: async (ctx) => {
    await requireDevUser(ctx);
    return stages.map(({ name, label, kind, inputs, handWritten, run, prompt }) => ({
      name,
      label,
      kind,
      inputs,
      hasHandWritten: handWritten !== undefined,
      canRun: run !== undefined || prompt !== undefined,
    }));
  },
});

export const createJob = mutation({
  args: { difficulty, seed: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const createdBy = await requireDevUser(ctx);
    return await ctx.db.insert("generationJobs", {
      seed: args.seed ?? Math.floor(Math.random() * 2 ** 31),
      difficulty: args.difficulty,
      createdBy,
      createdAt: Date.now(),
    });
  },
});

export const listJobs = query({
  args: {},
  handler: async (ctx) => {
    await requireDevUser(ctx);
    return await ctx.db.query("generationJobs").order("desc").take(50);
  },
});

export const listDrafts = query({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    return await ctx.db
      .query("generationDrafts")
      .withIndex("by_job_stage", (q) => q.eq("jobId", jobId))
      .collect();
  },
});

/**
 * Runs one stage on the job's existing drafts (or loads its hand-written output) and saves the result
 * as that stage's draft. AI stages run in the background (see aiAttempt); the page follows along live.
 */
export const runStage = action({
  args: { jobId: v.id("generationJobs"), stage: v.string(), handWritten: v.optional(v.boolean()) },
  handler: async (ctx, { jobId, stage: stageName, handWritten }): Promise<string[]> => {
    await requireDevUser(ctx);
    const stage = getStage(stageName);
    const { job, drafts } = await ctx.runQuery(internal.generation.jobs.loadInputs, { jobId, stages: stage.inputs });
    const missing = stage.inputs.filter((name) => !(name in drafts));
    if (missing.length > 0) throw new Error(`Run these stages first: ${missing.join(", ")}`);
    if (job.running) throw new Error(`The AI is still working on "${job.running.stage}".`);
    if (job.status === "queued" || job.status === "running") throw new Error("This case is being generated by Run all. Stop it first.");

    if (handWritten) {
      if (stage.handWritten === undefined) throw new Error("This stage has no hand-written version.");
      const checkErrors = checkOutput(stage, stage.handWritten, drafts, { seed: job.seed, difficulty: job.difficulty }, false);
      await ctx.runMutation(internal.generation.jobs.saveDraft, { jobId, stage: stage.name, output: stage.handWritten, checkErrors, source: "hand-written" });
      return checkErrors;
    }
    if (stage.run) return await runCodeStage(ctx, jobId, stage.name);
    if (!stage.prompt) throw new Error("The AI version of this stage isn't built yet. Use the hand-written one.");
    await ctx.runMutation(internal.generation.jobs.setRunning, { jobId, running: { stage: stage.name, attempt: 0 } });
    await ctx.scheduler.runAfter(0, internal.dev.tester.aiAttempt, { jobId, stage: stage.name, attempt: 0 });
    return [];
  },
});

/** Reruns an AI stage's checks on its saved output (useful after the checks change). */
export const recheckStage = action({
  args: { jobId: v.id("generationJobs"), stage: v.string() },
  handler: async (ctx, { jobId, stage: stageName }): Promise<string[]> => {
    await requireDevUser(ctx);
    const stage = getStage(stageName);
    const { job, drafts, previous } = await ctx.runQuery(internal.generation.jobs.loadInputs, { jobId, stages: stage.inputs, previousOf: stage.name });
    if (!previous) throw new Error("Nothing saved for this stage yet.");
    const checkErrors = checkOutput(stage, previous.output, drafts, { seed: job.seed, difficulty: job.difficulty }, previous.source === "llm");
    await ctx.runMutation(internal.generation.jobs.saveDraft, { jobId, stage: stage.name, output: previous.output, checkErrors, source: previous.source });
    return checkErrors;
  },
});

/**
 * One AI try at a stage. Each try is its own action so a slow model can't hit the action time limit.
 * If the checks fail and repairs are left, it schedules the next try with the problems.
 */
export const aiAttempt = internalAction({
  args: { jobId: v.id("generationJobs"), stage: v.string(), attempt: v.number() },
  handler: async (ctx, { jobId, stage, attempt }) => {
    try {
      const result = await runAiTry(ctx, jobId, stage, attempt);
      if (!result.error && result.retry) {
        await ctx.runMutation(internal.generation.jobs.setRunning, { jobId, running: { stage, attempt: attempt + 1 } });
        await ctx.scheduler.runAfter(0, internal.dev.tester.aiAttempt, { jobId, stage, attempt: attempt + 1 });
        return;
      }
    } catch (error) {
      await ctx.runMutation(internal.generation.jobs.setRunning, { jobId });
      throw error;
    }
    await ctx.runMutation(internal.generation.jobs.setRunning, { jobId });
  },
});

/** Clears a stuck "AI working" flag (e.g. if a background try was killed). */
export const stopWaiting = mutation({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    await ctx.db.patch(jobId, { running: undefined });
  },
});

export const getJob = query({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    return await ctx.db.get(jobId);
  },
});

export const listLogs = query({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    return await ctx.db
      .query("generationLogs")
      .withIndex("by_job", (q) => q.eq("jobId", jobId))
      .order("desc")
      .collect();
  },
});

/**
 * Record and replay: a job's AI-written stage outputs, to save under convex/fixtures/recorded/ as a
 * permanent test case. Run with: npx convex run dev/tester:exportJob '{"jobId":"..."}'
 */
export const exportJob = internalQuery({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    const job = await ctx.db.get(jobId);
    if (!job) throw new Error("Job not found.");
    const drafts = await ctx.db
      .query("generationDrafts")
      .withIndex("by_job_stage", (q) => q.eq("jobId", jobId))
      .collect();
    const outputs: Record<string, { output: unknown; source: string }> = {};
    for (const d of drafts) if (d.source !== "code") outputs[d.stage] = { output: d.output, source: d.source };
    return { jobId, seed: job.seed, difficulty: job.difficulty, outputs };
  },
});

/** Generates the whole case in the background: every stage in order, with repairs. */
export const runAll = mutation({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    const job = await ctx.db.get(jobId);
    if (!job) throw new Error("Job not found.");
    if (job.running || job.status === "queued" || job.status === "running") throw new Error("This case is already being generated.");
    const workflowId = await workflow.start(ctx, internal.generation.workflow.generateCase, { jobId });
    await ctx.db.patch(jobId, { status: "queued", workflowId, failedStage: undefined, error: undefined, startedAt: undefined, finishedAt: undefined });
  },
});

/** A test run's difficulty mix. */
const TEST_MIX = ["easy", "normal", "hard"] as const;

/** Starts a test run: 3 new cases (one per difficulty) with random seeds, generated one after another. */
export const runTestBatch = mutation({
  args: {},
  handler: async (ctx) => {
    const createdBy = await requireDevUser(ctx);
    const batch = `Test run ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`;
    const jobIds: Id<"generationJobs">[] = [];
    for (const level of TEST_MIX) {
      const seed = Math.floor(Math.random() * 2 ** 31);
      jobIds.push(await ctx.db.insert("generationJobs", { seed, difficulty: level, createdBy, createdAt: Date.now(), status: "queued", batch }));
    }
    const workflowId = await workflow.start(ctx, internal.generation.workflow.generateBatch, { jobIds });
    for (const jobId of jobIds) await ctx.db.patch(jobId, { workflowId });
    return batch;
  },
});

/** Stops a Run all or a whole test run; finished cases keep their result. */
export const stopRun = mutation({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    const job = await ctx.db.get(jobId);
    if (!job?.workflowId) throw new Error("This case isn't being generated.");
    await workflow.cancel(ctx, job.workflowId as Parameters<typeof workflow.cancel>[1]);
    const jobs = job.batch ? await ctx.db.query("generationJobs").withIndex("by_batch", (q) => q.eq("batch", job.batch)).collect() : [job];
    for (const j of jobs) {
      if (j.status === "queued" || j.status === "running") await ctx.db.patch(j._id, { status: "stopped", running: undefined, finishedAt: Date.now() });
    }
  },
});

/** Test run labels, newest first. */
export const listBatches = query({
  args: {},
  handler: async (ctx) => {
    await requireDevUser(ctx);
    const jobs = await ctx.db.query("generationJobs").order("desc").take(200);
    return [...new Set(jobs.map((j) => j.batch).filter((b): b is string => !!b))];
  },
});

const aiStageNames = stages.filter((s) => s.kind === "llm").map((s) => s.name);

/** Drafts and AI call logs for some jobs, trimmed to what the stats need. */
async function statsInputs(ctx: QueryCtx, jobs: Doc<"generationJobs">[]) {
  const drafts = [];
  const logs = [];
  for (const job of jobs) {
    const jobDrafts = await ctx.db.query("generationDrafts").withIndex("by_job_stage", (q) => q.eq("jobId", job._id)).collect();
    drafts.push(...jobDrafts.map((d) => ({ jobId: d.jobId as string, stage: d.stage, checkErrors: d.checkErrors })));
    const jobLogs = await ctx.db.query("generationLogs").withIndex("by_job", (q) => q.eq("jobId", job._id)).collect();
    logs.push(
      ...jobLogs.map((l) => ({
        jobId: l.jobId as string,
        stage: l.stage,
        attempt: l.attempt,
        ms: l.ms,
        inputTokens: l.inputTokens,
        outputTokens: l.outputTokens,
        problems: l.problems,
        error: l.error,
      })),
    );
  }
  return { drafts, logs };
}

/** One test run's results: each case, and each AI stage across the cases. */
export const batchStats = query({
  args: { batch: v.string() },
  handler: async (ctx, { batch }) => {
    await requireDevUser(ctx);
    const jobs = await ctx.db.query("generationJobs").withIndex("by_batch", (q) => q.eq("batch", batch)).collect();
    const { drafts, logs } = await statsInputs(ctx, jobs);
    const statsJobs = jobs.map((j) => ({
      id: j._id as string,
      difficulty: j.difficulty,
      seed: j.seed,
      status: j.status,
      failedStage: j.failedStage,
      error: j.error,
      startedAt: j.startedAt,
      finishedAt: j.finishedAt,
    }));
    return { jobs: jobSummaries(statsJobs, logs), stages: stageStats(aiStageNames, drafts, logs) };
  },
});

/** How many past cases a prediction averages over. */
const HISTORY = 5;

/** Predicted AI minutes left for a job, from the last few passed cases of the same difficulty. */
export const predictTime = query({
  args: { jobId: v.id("generationJobs") },
  handler: async (ctx, { jobId }) => {
    await requireDevUser(ctx);
    const job = await ctx.db.get(jobId);
    if (!job || job.status === "passed" || job.status === "failed" || job.status === "stopped") return null;
    const recent = await ctx.db.query("generationJobs").order("desc").take(200);
    const history = recent.filter((j) => j.status === "passed" && j.difficulty === job.difficulty).slice(0, HISTORY);
    if (history.length === 0) return null;
    const { drafts, logs } = await statsInputs(ctx, history);
    const done = await ctx.db.query("generationDrafts").withIndex("by_job_stage", (q) => q.eq("jobId", jobId)).collect();
    const left = aiStageNames.filter((name) => job.running?.stage === name || !done.some((d) => d.stage === name));
    const minutesLeft = predictMinutesLeft(left, stageStats(aiStageNames, drafts, logs));
    return minutesLeft === undefined ? null : { minutesLeft, basedOn: history.length };
  },
});
